# Generated by Django 5.1.2 on 2025-02-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='active',
            new_name='is_active',
        ),
    ]
